#!/usr/bin/python3

import structures_collection.auto_segmentation as auto_segmentation
import structures_collection.dependency as dependency
import structures_collection.auto_parameter_extraction as auto_parameter_extraction
import structures_collection.static as static
import structures_collection.sharp_function as sharp_function
import structures_collection.layer_extraction as layer_extraction
